name = "adors-dev"
main = ".open-next/worker.js"
compatibility_date = "2026-05-28"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = ".open-next/assets"
binding = "ASSETS"

[vars]
GITHUB_ID = "75393390"
INSTAGRAM_ID = "123456789"
LINKEDIN_ID = "123456789"